[package]
name = "tutorial-rust"
version = "0.1.0"
authors = ["bragaz <leo.braga95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"